### ISSUE TITLE
Request for all cells voltages displaying feature.

### ISSUE THREAD

**Issue by xury77** [mr-manuel/venus-os_dbus-mqtt-battery#1]
Hi mr-manuel.
First of all I'd like to send you very big thanks for this feature. This is what I looking for very long time!
I'd like to asking you about new feature such as displaying all cell voltages in details tab. 
I've got my custom  battery with  custom BMS and I can send all cell voltages to MQTT broker. It will be very nice to see these all voltages in Victron. It would also be useful to display delta voltage value.
I can also confirm that it works correctly on CerboGX.

**Comment by mr-manuel** [comment]
Hi @xury77,
how many cell voltages do you have?

**Comment by xury77** [comment]
It would be great. I've used dbus-serialbattery in the past. Plugin is ok, but Daly BMS not so. 
Yet one question: How to add second battery instance?

**Comment by mr-manuel** [comment]
Just released a complete new version.

Check the [Multiple instances](https://github.com/mr-manuel/venus-os_dbus-mqtt-battery/tree/v1.0.0#multiple-instances) section in the README.

Please give me a feedback, if all is working on your side.

**Comment by xury77** [comment]
Awesome. Working like a harm.

**Comment by mr-manuel** [comment]
@xury77 harm doesn't mean anything good.

**Comment by xury77** [comment]
Hi  **@mr-manuel** its me again -  your annoying issue maker :)
Last question (I hope): Missing HighCellVoltage in Alarms is not provided by Victron ?
I see "LowCellVoltage" but no "HighCellVoltage"

**Comment by mr-manuel** [comment]
Hi @xury77,
indeed this alarm is not provided by Victron. See the [dbus documentation](https://github.com/victronenergy/venus/wiki/dbus#battery). Also if you check the QML files you cannot find this value.

**Comment by xury77** [comment]
Yes you are right. It seems they don't control this value in their BMS. Or this situation may never occur.

**Comment by xury77** [comment]
Sorry one  more question about "MinVoltageCellId" and others. You wrote:

> "MinVoltageCellId": "C3",             --> String - ID of the cell with the lowest voltage - if empty, than gets calculated when elements in "Voltages" are present
        "MinCellVoltage": 3.392,              --> Volt - Of the cell with the lowest voltage - if empty, than gets calculated when elements in "Voltages" are present

> 
What exactly mean "if empty"? I asking because I tried:
Not to send this property
Sending as null

> msg.payload.System.MinVoltageCellId = null;
msg.payload.System.MinCellVoltage = null;
msg.payload.System.MaxVoltageCellId = null;
msg.payload.System.MaxCellVoltage = null;``


Sending string properties as empty string:

> msg.payload.System.MinVoltageCellId = ""; 
   msg.payload.System.MinCellVoltage = null;


And still no values on Detalis page and also no Voltage sum nor Min/Max/Diff
But cell voltages are present.
Perhaps I have to send also empty messages to MinTemperatureCellId and others witch I not use?

**Comment by mr-manuel** [comment]
I changed the desciption to "if missing in the JSON". Can you post the JSON that you sent?

**Comment by xury77** [comment]
My payload:
``{"Dc":{"Power":0,"Voltage":52.61,"Current":0,"Temperature":19},"InstalledCapacity":400,"ConsumedAmphours":-340.2,"Capacity":124.5,"Soc":19,"Alarms":{"LowVoltage":0,"HighVoltage":0,"LowSoc":0,"LowTemperature":0,"HighTemperature":0},"Info":{"ChargeRequest":false,"MaxChargeVoltage":58.9,"MaxChargeCurrent":400,"MaxDischargeCurrent":800},"History":{"ChargeCycles":7,"TotalAhDrawn":1313.7},"System":{"NrOfModulesOnline":1,"NrOfModulesOffline":0},"Voltages":{"Cell1":3.281,"Cell2":3.29,"Cell3":3.286,"Cell4":3.289,"Cell5":3.298,"Cell6":3.276,"Cell7":3.293,"Cell8":3.288,"Cell9":3.296,"Cell10":3.295,"Cell11":3.298,"Cell12":3.294,"Cell13":3.292,"Cell14":3.296,"Cell15":3.296,"Cell16":3.297},"Io":{"AllowToCharge":1,"AllowToDischarge":1}}``

**Comment by mr-manuel** [comment]
> BTW "Alarms" can't be a bools as it a three state values: 0 -OK 1-Warning 2-Alarm

Nice catch, thanks. I corrected it.

`"ConsumedAmphours": -340.2,` should not be negative, but this is not causing the problem.

The problem was a division by zero when current = 0 in the Time to Go calculation. I publish a new release.

**Comment by xury77** [comment]
I can confirm - working :)
btw. I get this negative value directly from SmartShunt so I use Math.abs() to convert it.
Once again Very Thanks for this handy plugin.

**Comment by pkkrusty** [comment]
> Hi [@xury77](https://github.com/xury77), displaying the cell voltages is not a native feature of Venus OS, but I will add this soon the same way it is the [dbus-serialbattery](https://github.com/Louisvdw/dbus-serialbattery) driver.

Did this ever happen? I'm using the full MQTT spec, and json message includes all cell voltages, but I don't see cell voltages in detail menu, just min and max.

<edit> I see that the cell voltages menu does exist as per the screenshots. but I'm not seeing that in my instance. Here's an example JSON I am sending:
```
{
    "Dc": {
        "Voltage": 49.329,
        "Current": -0.613,
        "Power": -30.23868,
        "Temperature": 32
    },
    "Soc": 96,
    "InstalledCapacity": 40,
    "Capacity": 38.253,
    "ConsumedAmphours": 1.746998,
    "Balancing": 0,
    "TimeToGo": 2.361809e7,
    "History": {
        "ChargeCycles": 0
    },
    "Voltages": {
        "Cell1": 4.11,
        "Cell2": 4.109,
        "Cell3": 4.109,
        "Cell4": 4.11,
        "Cell5": 4.11,
        "Cell6": 4.108,
        "Cell7": 4.113,
        "Cell8": 4.113,
        "Cell9": 4.112,
        "Cell10": 4.11,
        "Cell11": 4.11,
        "Cell12": 4.109
    },
    "Balances": {
        "Cell1": 0,
        "Cell2": 0,
        "Cell3": 0,
        "Cell4": 0,
        "Cell5": 0,
        "Cell6": 0,
        "Cell7": 0,
        "Cell8": 0,
        "Cell9": 0,
        "Cell10": 0,
        "Cell11": 0,
        "Cell12": 0,
        "Cell13": 0
    },
    "System": {
        "MinCellVoltage": 4.108,
        "MaxCellVoltage": 4.113,
        "MinVoltageCellId": "Cell6",
        "MaxVoltageCellId": "Cell7"
    },
    "Info": {
        "MaxChargeCurrent": 100,
        "MaxDischargeCurrent": 200,
        "MaxChargeVoltage": 50.16
    }
}
```
