### ISSUE TITLE
Charge Current Limit based on Time of Day + General Battery Monitor Question

### ISSUE THREAD

**Issue by J4nsen** [mr-manuel/venus-os_dbus-mqtt-battery#11]
Hi,
I found this repo through your link in a dbus-serial-battery issue and was wondering, if I could use them together.

Basically I want to limit the Charge/Discharge Current based on the time of day. My problem is the noise my three Multiplus 2s create when turning on the fans, and since my bedroom is located next to them, preventing the fans to turn on during my sleep would be nice. 

However, (atm) I only want to change the Charge and Discharge Current through Node-Red and let the other logic reside in dbus-serial-battery. Is this possible? 

This also leads to my next question: Currently I have the Multiplus as my Battery Monitor selected. However dbus-serial-battery still imposes its parameters. Who is actually in charge of the limits?

Thanks in advance, Jan

**Comment by J4nsen** [comment]
Hey,
thanks for your fast answer and thanks for your suggestion. I will test the Victron Energy Nodes. :)

Yes, I've enabled ESS and DVCC. But I dont understand why dbus-serialbattery works, when i've set the battery monitor to the Multiplus. 

Anyway, this issue has nothing to do with your project.

**Comment by mr-manuel** [comment]
Then this is the node you are searching for:

![grafik](https://user-images.githubusercontent.com/12592765/232101997-525efa29-7b1b-4b77-801e-a16fdf1e0527.png)

Why should dbus-serialbattery not work? You can have more than one battery monitore. Some have even more than 5 batteries.

**Comment by J4nsen** [comment]
Thanks!

You said

>> if you have selected the MultiPlus as battery monitor, than the MultiPlus set the CCL and DCL.

and I assumed that with the multiplus as the monitor, dbus-serialbatterys settings regarding CCL and DCL would have no effect. How would different monitors work if they calculate/set different values for CCL and DCL?

**Comment by mr-manuel** [comment]
It gets only the value from the selected monitor.

**Comment by pos-ei-don** [comment]
> It gets only the value from the selected monitor.

I think that this is only mostly true.
When a single BMS lowers the Max Charge Current,  I belive the lowest one is used. I bet I saw this behabiour several Times...

**Comment by mr-manuel** [comment]
Maybe best would be, if you ask in the victron community.

**Comment by J4nsen** [comment]
Thanks 👍

I will also post my findings there. Probably tomorrow

**Comment by mr-manuel** [comment]
Ok, so the Victron Community got an answer :)
The battery monitor is not the same as the BMS selected.

With Venus OS >3.00 you can select the BMS that should be used for DVCC:
![grafik](https://user-images.githubusercontent.com/12592765/232209754-532dd384-e203-4694-92d8-8e60971144e0.png)

**Comment by J4nsen** [comment]
Thank you so much for the research! So everything works as expected by the Victron engineers :D

I'm still unsure how I will implement my idea. I will have a look at the ESS Control Node :)

**Comment by J4nsen** [comment]
The ESS Control Node works nicely. Thanks again :)

![image](https://user-images.githubusercontent.com/3029093/235301073-6e4544ac-b034-4e15-9079-bffeb3de1fda.png)

**Comment by mr-manuel** [comment]
Nice, can you explain more detailed what exactly you did? Maybe this could also be interesting for others :-)

**Comment by J4nsen** [comment]
Sure :)

I started with updating my Venus Controller to the large image to get NodeRed.

In NodeRed I created my flow to set the maximum charge current to 50A based on the day of time. It's simple:
![image](https://user-images.githubusercontent.com/3029093/235322442-2e306e55-c2df-4661-819e-d1e89c6f862c.png)

The first node is [light scheduler](https://flows.nodered.org/node/node-red-contrib-light-scheduler): 
![image](https://user-images.githubusercontent.com/3029093/235322496-48d59653-8d88-4353-bbcf-9d0b2642f4a0.png)

It outputs ON/OFF as the payload, which in the end sends either to 50, or -1 to the "ESS Control" Node. The value -1 disables the current limit.
![image](https://user-images.githubusercontent.com/3029093/235322578-35a0a36b-a6a8-42c1-8f88-395cc8431d26.png)

Here my exported flow: [ESS-Current-by-daytime.txt](https://github.com/mr-manuel/venus-os_dbus-mqtt-battery/files/11360022/ESS-Current-by-daytime.txt)
