### ISSUE TITLE
difference between "config.default.ini" and  "config.sample.ini"

### ISSUE THREAD

**Issue by pos-ei-don** [mr-manuel/venus-os_dbus-mqtt-battery#12]
Can you please clarify, what the difference between
"config.default.ini" and  "config.sample.ini" and "config.ini" is?

In the Releasenote you wrote "config.default.ini" (see footer ), but the file I find
 "config.sample.ini.
As I understand is  "config.ini" MY configfile where i can change defaults from "config.default.ini".

* Is "config.sample.ini" never read? 

Is  "config.default.ini" still used as you wrote: 
> Copy or rename the config.sample.ini to config.ini in the dbus-mqtt-battery folder and change it as you need it.

Thank you!!

----

Footer

[v0.1.0](https://github.com/mr-manuel/venus-os_dbus-mqtt-battery/releases/tag/v0.1.0)
    Added: Set logging level in config.default.ini

**Comment by pos-ei-don** [comment]
I thought that the driver will read all default values from `config.default.ini` 
and just overwrite my "custom" changes with values from my personal "config.ini"
for easy updates. 

So I used this the wrong way!
Thank you for clarifying.

**Comment by mr-manuel** [comment]
That is the behaviour from the `dbus-serialbattery` driver, since it works also without changing setting. But with this driver you need to specify IP address of the MQTT broker and the topic.
