### ISSUE TITLE
BIG Success, but few things to iron out issue #1

### ISSUE THREAD

**Issue by seamaster101** [mr-manuel/venus-os_dbus-mqtt-battery#13]
@mr-manuel after couple of long night (5am) I finally manage to get my batteries shown on venus OS!
Thank you for the great repository!
<img width="547" alt="image" src="https://github.com/mr-manuel/venus-os_dbus-mqtt-battery/assets/7897023/c978b5fb-5bc1-4fc0-8d62-ef542e2abe23">
I double checked every cell data and all comes true!
On the way I experienced many problems with my implementation (it was me not you... LOL), but few issues were persistent and i could not resolve, thus the title.
Please help with these:
Issue 1:
When RPI is restarted, it losses the drivers and I have to manually run `bash install.sh` for each of the 4 drivers 
 Not sure what to do here... Any suggestions?

**Comment by mr-manuel** [comment]
How did you install the 4 drivers?

Can you post the output of this commands?

```bash
cat /data/rc.local

ls -l /data/etc

head -n 100 /data/etc/dbus-mqtt-*/config.ini
```

**Comment by seamaster101** [comment]
@mr-manuel I installed the 4 drivers following your recipe for multiple drivers.
here is the output of the `cat /data/rc.local`
<img width="711" alt="image" src="https://github.com/mr-manuel/venus-os_dbus-mqtt-battery/assets/7897023/465cac8c-311c-4aba-9d38-55f1d6664f39">
here is the output of `ls -l /data/etc`
<img width="733" alt="image" src="https://github.com/mr-manuel/venus-os_dbus-mqtt-battery/assets/7897023/7b654164-fcc8-4996-8dc0-f0214d8f7aa0">
here is the output of `head -n 100 /data/etc/dbus-mqtt-*/config.ini`
`root@raspberrypi2:/data/etc# head -n 100 /data/etc/dbus-mqtt-*/config.ini
==> /data/etc/dbus-mqtt-battery-1/config.ini <==
; CONFIG FILE
; GitHub reporitory: https://github.com/mr-manuel/venus-os_dbus-mqtt-battery
; remove semicolon ; to enable desired setting

[DEFAULT]
; Set logging level
; ERROR = shows errors only
; WARNING = shows ERROR and warnings
; INFO = shows WARNING and running functions
; DEBUG = shows INFO and data/values
; default: WARNING
logging = WARNING

; Device name
; default: MQTT Battery
device_name = Battery-1

; Device VRM instance
; default: 41
device_instance = 42

; Specify after how many seconds the driver should exit (disconnect), if no new MQTT message was received
; default: 60
; value to disable timeout: 0
timeout = 60


[TIME_TO_GO]
; Calculates the Time-To-Go shown in the GUI
; 0 = Disabled
; 1 = Enabled
enabled = 1
; Specify the SoC which is used for calculation
; default: 10
soc = 10
; Specify in seconds how often the Time-To-Go should be recalculated
; Minimum are 5 seconds to prevent CPU overload
; default: 300
recalculate_every = 10


[MQTT]
; IP addess or FQDN from MQTT server
broker_address = 192.168.88.110

; Port of the MQTT server
; default plaintext: 1883
; default TLS port: 8883
broker_port = 1883

; Enables TLS
; 0 = Disabled
; 1 = Enabled
;tls_enabled = 0

; Absolute path to the Certificate Authority certificate file that is to be treated as trusted by this client
;tls_path_to_ca = /data/keys/mosquitto.crt

; Disables verification of the server hostname in the server certificate
; 0 = Disabled
; 1 = Enabled
;tls_insecure = 1

; Username used for connection
;username = myuser

; Password used for connection
;password = mypassword

; Topic where the meters data as JSON string is published
; minimum required JSON payload: { "Dc": { "Power": 321.6, "Voltage": 52.6  }, "Soc": 63 }
;topic = enphase/battery
topic = battery-1


==> /data/etc/dbus-mqtt-battery-2/config.ini <==
; CONFIG FILE
; GitHub reporitory: https://github.com/mr-manuel/venus-os_dbus-mqtt-battery
; remove semicolon ; to enable desired setting

[DEFAULT]
; Set logging level
; ERROR = shows errors only
; WARNING = shows ERROR and warnings
; INFO = shows WARNING and running functions
; DEBUG = shows INFO and data/values
; default: WARNING
logging = WARNING

; Device name
; default: MQTT Battery
device_name = Battery-2

; Device VRM instance
; default: 41
device_instance = 43

; Specify after how many seconds the driver should exit (disconnect), if no new MQTT message was received
; default: 60
; value to disable timeout: 0
timeout = 60


[TIME_TO_GO]
; Calculates the Time-To-Go shown in the GUI
; 0 = Disabled
; 1 = Enabled
enabled = 1
; Specify the SoC which is used for calculation
; default: 10
soc = 10
; Specify in seconds how often the Time-To-Go should be recalculated
; Minimum are 5 seconds to prevent CPU overload
; default: 300
recalculate_every = 10


[MQTT]
; IP addess or FQDN from MQTT server
broker_address = 192.168.88.110

; Port of the MQTT server
; default plaintext: 1883
; default TLS port: 8883
broker_port = 1883

; Enables TLS
; 0 = Disabled
; 1 = Enabled
;tls_enabled = 0

; Absolute path to the Certificate Authority certificate file that is to be treated as trusted by this client
;tls_path_to_ca = /data/keys/mosquitto.crt

; Disables verification of the server hostname in the server certificate
; 0 = Disabled
; 1 = Enabled
;tls_insecure = 1

; Username used for connection
;username = myuser

; Password used for connection
;password = mypassword

; Topic where the meters data as JSON string is published
; minimum required JSON payload: { "Dc": { "Power": 321.6, "Voltage": 52.6  }, "Soc": 63 }
;topic = enphase/battery
topic = battery-2


==> /data/etc/dbus-mqtt-battery-3/config.ini <==
; CONFIG FILE
; GitHub reporitory: https://github.com/mr-manuel/venus-os_dbus-mqtt-battery
; remove semicolon ; to enable desired setting

[DEFAULT]
; Set logging level
; ERROR = shows errors only
; WARNING = shows ERROR and warnings
; INFO = shows WARNING and running functions
; DEBUG = shows INFO and data/values
; default: WARNING
logging = WARNING

; Device name
; default: MQTT Battery
device_name = Battery-3

; Device VRM instance
; default: 41
device_instance = 44

; Specify after how many seconds the driver should exit (disconnect), if no new MQTT message was received
; default: 60
; value to disable timeout: 0
timeout = 60


[TIME_TO_GO]
; Calculates the Time-To-Go shown in the GUI
; 0 = Disabled
; 1 = Enabled
enabled = 1
; Specify the SoC which is used for calculation
; default: 10
soc = 10
; Specify in seconds how often the Time-To-Go should be recalculated
; Minimum are 5 seconds to prevent CPU overload
; default: 300
recalculate_every = 10


[MQTT]
; IP addess or FQDN from MQTT server
broker_address = 192.168.88.110

; Port of the MQTT server
; default plaintext: 1883
; default TLS port: 8883
broker_port = 1883

; Enables TLS
; 0 = Disabled
; 1 = Enabled
;tls_enabled = 0

; Absolute path to the Certificate Authority certificate file that is to be treated as trusted by this client
;tls_path_to_ca = /data/keys/mosquitto.crt

; Disables verification of the server hostname in the server certificate
; 0 = Disabled
; 1 = Enabled
;tls_insecure = 1

; Username used for connection
;username = myuser

; Password used for connection
;password = mypassword

; Topic where the meters data as JSON string is published
; minimum required JSON payload: { "Dc": { "Power": 321.6, "Voltage": 52.6  }, "Soc": 63 }
;topic = enphase/battery
topic = battery-3


==> /data/etc/dbus-mqtt-battery/config.ini <==
; CONFIG FILE
; GitHub reporitory: https://github.com/mr-manuel/venus-os_dbus-mqtt-battery
; remove semicolon ; to enable desired setting

[DEFAULT]
; Set logging level
; ERROR = shows errors only
; WARNING = shows ERROR and warnings
; INFO = shows WARNING and running functions
; DEBUG = shows INFO and data/values
; default: WARNING
logging = WARNING

; Device name
; default: MQTT Battery
device_name = Combined Battery Bank

; Device VRM instance
; default: 41
device_instance = 41

; Specify after how many seconds the driver should exit (disconnect), if no new MQTT message was received
; default: 60
; value to disable timeout: 0
timeout = 60


[TIME_TO_GO]
; Calculates the Time-To-Go shown in the GUI
; 0 = Disabled
; 1 = Enabled
enabled = 1
; Specify the SoC which is used for calculation
; default: 10
soc = 10
; Specify in seconds how often the Time-To-Go should be recalculated
; Minimum are 5 seconds to prevent CPU overload
; default: 300
recalculate_every = 10


[MQTT]
; IP addess or FQDN from MQTT server
broker_address = 192.168.88.110

; Port of the MQTT server
; default plaintext: 1883
; default TLS port: 8883
broker_port = 1883

; Enables TLS
; 0 = Disabled
; 1 = Enabled
;tls_enabled = 0

; Absolute path to the Certificate Authority certificate file that is to be treated as trusted by this client
;tls_path_to_ca = /data/keys/mosquitto.crt

; Disables verification of the server hostname in the server certificate
; 0 = Disabled
; 1 = Enabled
;tls_insecure = 1

; Username used for connection
;username = myuser

; Password used for connection
;password = mypassword

; Topic where the meters data as JSON string is published
; minimum required JSON payload: { "Dc": { "Power": 321.6, "Voltage": 52.6  }, "Soc": 63 }
;topic = enphase/battery
topic = housebatterybank'

**Comment by mr-manuel** [comment]
> @mr-manuel I installed the 4 drivers following your recipe for multiple drivers. here is the output of the `cat /data/rc.local` <img alt="image" width="711" src="https://user-images.githubusercontent.com/7897023/237210034-465cac8c-311c-4aba-9d38-55f1d6664f39.png">

Try to move the lines from the `dbus-mqtt-battery*` after the lines from the `dbus-serialbattery`

**Comment by seamaster101** [comment]
Succes! 
here is the file now:
`root@raspberrypi2:~# cat /data/rc.local
#!/bin/bash
sh /data/etc/dbus-serialbattery/reinstalllocal.sh
ln -s /data/drivers/dbus-mqtt-devices-0.6.2/bin/service /service/dbus-mqtt-devices
bash /data/etc/dbus-mqtt-battery/install.sh
bash /data/etc/dbus-mqtt-battery-1/install.sh
bash /data/etc/dbus-mqtt-battery-2/install.sh
bash /data/etc/dbus-mqtt-battery-3/install.sh
/usr/bin/python /data/classic/charger/charger.py
/usr/bin/python /data/classic/battery/battery.py
root@raspberrypi2:~#`
You can close this one! Big thank you again!

**Comment by seamaster101** [comment]
See above! it is working now
