### ISSUE TITLE
MQTT Battery and Aggregate Battery possible?

### ISSUE THREAD

**Issue by Zahnpasta83** [mr-manuel/venus-os_dbus-mqtt-battery#17]
Is there a way to integrate data from a battery based on MQTT Battery together with batteries based on Serial Battery in Aggregate Battery?

**Comment by pos-ei-don** [comment]
Of course! Take a look at Manuels repository.

**Comment by Zahnpasta83** [comment]
🤷🏻‍♂️ which one? Can you link it?

**Comment by pos-ei-don** [comment]
What is wrong with this one you are currently in?

**Comment by mr-manuel** [comment]
If you aleady have installed [`dbus-mqtt-battery`](https://github.com/mr-manuel/venus-os_dbus-mqtt-battery) and [`dbus-serialbattery`](https://github.com/Louisvdw/dbus-serialbattery) they should be both visible in [dbus-aggregate-batteries](https://github.com/Dr-Gigavolt/dbus-aggregate-batteries). If not you could try [BatteryAggregator](https://github.com/pulquero/BatteryAggregator).

**Comment by mr-manuel** [comment]
Linked issue: https://github.com/Dr-Gigavolt/dbus-aggregate-batteries/issues/51
