### ISSUE TITLE
Logic advise for discharging battery

### ISSUE THREAD

**Issue by kopierschnitte** [mr-manuel/venus-os_dbus-mqtt-battery#27]
Hi!

Thanks for the great project. It enabled me to make my non-Victron ESS visible within VRM.

At the moment, I don't really understand how charging/discharging is handled by your driver or, better said, by VenusOS.

If my external battery is charged, VenusOS automatically adds this to the AC-Load of my entire installation and if it's being discharged, I needed to "fake" solar production with a custom inverter driver in order to have correct AC-Loads.

This of course disturbs my solar statistics and therefore also the production forecast.

Do you see any possibility that your driver could also correctly "inject" charging/discharging? Or didn't I understand the logic correctly at this point?

**Comment by mr-manuel** [comment]
You need a MultiPlus to achieve that, since you want to merge DC with AC.

See https://github.com/mr-manuel/venus-os_dbus-multiplus-emulator

**Comment by kopierschnitte** [comment]
Well, I do have a MP2 with a connected 48V battery ;-)

**Comment by mr-manuel** [comment]
Then you probably have a configuration issue somewhere. In this case ask your question in the [Victron Community](https://community.victronenergy.com/).

**Comment by kopierschnitte** [comment]
Thanks! But do you think, VenusOS even respects those kind of (dbus-connected) batteries or does it just displays the statistics without doing anything with the data?

**Comment by mr-manuel** [comment]
It doesn't matter how you connect a battery in Venus OS. When it is recognized, all batteries should display the same way.

**Comment by kopierschnitte** [comment]
Okay, then I suspect that something's wrong if my battery is shown like this in VRM, isn't it?
![Screenshot_20240914_124155_VRM](https://github.com/user-attachments/assets/82fbd775-571a-4842-81cf-b5c8fe5c8ffc)
The Cerbo itself displays it as expected:
![Screenshot_20240914_124523_Edge](https://github.com/user-attachments/assets/d81c8942-4239-46b2-b2f7-627c16ba74ed)

**Comment by mr-manuel** [comment]
See https://github.com/mr-manuel/venus-os_dbus-mqtt-battery/issues/27#issuecomment-2350935676
