### ISSUE TITLE
Phase issue battery

### ISSUE THREAD

**Issue by krulkip** [mr-manuel/venus-os_dbus-mqtt-battery#32]
My battery is on phase L3 but it is shown on L1 and discharging battery is shown as a power usage instead of power generating. Could you tell me where i could fix that please.

**Comment by mr-manuel** [comment]
A battery has only DC and not AC. So it can't be on no AC phase without inverter. Are you using any Victron products?

**Comment by krulkip** [comment]
Yes multiplus2
    On Tuesday 5 November 2024 at 20:37:35 CET, Manuel ***@***.***> wrote:  
 
 


A battery has only DC and not AC. So it can't be on an AC phase without inverter. Are you using any Victron products?

**Comment by mr-manuel** [comment]
Then very likely you have misconfigured that. Please ask the Victron Community on how to set a MultiPlus on L3 instead of L1.

Post a link here, so it helps others.
