### ISSUE TITLE
Feature request: round Amps to 1f

### ISSUE THREAD

**Issue by pos-ei-don** [mr-manuel/venus-os_dbus-mqtt-battery#5]
I have a lot of Devices, and Amps are formated to 1 for (almost) all devices.
This driver has 2, so reading and comparing several Devices in the HX-Console is a (little!) bit harder.

Can you format this with 1f or can this be part of the config.ini?

If you prefer, I can also change the code only in my installation, but this will brake default updates.

**Comment by mr-manuel** [comment]
Oh, ok. I was only looking at the dbus-serialbattery. Thanks for clearing up. I will change that.

Can you check how many decimals you see for `Ah`, `%` and Temperature?

**Comment by pos-ei-don** [comment]
Ah=1
V=2
%=0
W=1, bit sometimes 0, but i think this is only on very small numbers.
°=0 (In Multiplus, etc), but i have removed all batteries so i cannot tell currently if this is the same there.

**Comment by mr-manuel** [comment]
https://github.com/mr-manuel/venus-os_dbus-mqtt-battery/commit/46ef53da21eeb589f4f2177a6b0bcdd7ab587635

I recreated the v1.0.2 release with this changes.
